"""Миграции: совпадение с моделями и stairway-тест (ADR-0011, ADR-0013).

Тесты синхронные: env.py Alembic сам запускает asyncio.run().
"""

import asyncio

import pytest
from alembic import command
from alembic.script import ScriptDirectory
from sqlalchemy import make_url, text
from sqlalchemy.ext.asyncio import create_async_engine
from testcontainers.community.postgres import PostgresContainer

from tests.support import alembic_config

DATABASE = "migrations_check"


async def _recreate_database(admin_url: str) -> None:
    engine = create_async_engine(admin_url, isolation_level="AUTOCOMMIT")
    async with engine.connect() as connection:
        await connection.execute(text('DROP DATABASE IF EXISTS "migrations_check"'))
        await connection.execute(text('CREATE DATABASE "migrations_check"'))
    await engine.dispose()


@pytest.fixture
def empty_database_url(postgres: PostgresContainer) -> str:
    """Отдельная пустая база в том же контейнере — не мешает основной тестовой."""
    admin_url = postgres.get_connection_url()
    asyncio.run(_recreate_database(admin_url))
    return make_url(admin_url).set(database=DATABASE).render_as_string(hide_password=False)


def test_upgrade_head_matches_models(empty_database_url: str) -> None:
    config = alembic_config(empty_database_url)

    command.upgrade(config, "head")

    # AutogenerateDiffsDetected, если модели и миграции разошлись.
    command.check(config)


def test_stairway(empty_database_url: str) -> None:
    config = alembic_config(empty_database_url)
    revisions = list(ScriptDirectory.from_config(config).walk_revisions("base", "heads"))

    assert revisions, "нет ни одной миграции"
    for revision in reversed(revisions):
        command.upgrade(config, revision.revision)
        command.downgrade(config, "-1")
        command.upgrade(config, revision.revision)


async def _seed_legacy_event_payloads(url: str) -> None:
    import json
    from datetime import UTC, datetime
    from uuid import uuid7

    from grocery.domain.enums import EventType
    from grocery.schemas.items import ItemRead
    from grocery.schemas.tags import TagRead

    engine = create_async_engine(url)
    user_id, list_id = uuid7(), uuid7()
    item = ItemRead(
        id=uuid7(),
        shopping_list_id=list_id,
        name="Лук",
        quantity=None,
        unit=None,
        note=None,
        tags=[],
        sources=[],
        is_bought=False,
        bought_at=None,
        created_at=datetime.now(UTC),
        updated_at=datetime.now(UTC),
    )
    tag = TagRead(id=uuid7(), name="Овощи").model_dump(mode="json")
    try:
        async with engine.begin() as conn:
            await conn.execute(
                text(
                    "INSERT INTO users (id, username, password_hash) "
                    "VALUES (:id, 'migration', 'hash')"
                ),
                {"id": user_id},
            )
            await conn.execute(
                text(
                    "INSERT INTO shopping_lists (id, owner_id, name) "
                    "VALUES (:id, :owner, 'Покупки')"
                ),
                {"id": list_id, "owner": user_id},
            )
            for type in EventType:
                payload: dict[str, object] = {
                    "items": [],
                    "results": [],
                    "tag": None,
                    "previous_tag": None,
                }
                if type == EventType.ITEMS_ADDED:
                    payload["results"] = [
                        {"status": "created", "item": item.model_dump(mode="json")}
                    ]
                elif type in (EventType.TAG_RENAMED, EventType.TAGS_MERGED):
                    payload.update(tag=tag, previous_tag=tag)
                elif type == EventType.TAG_DELETED:
                    payload["tag"] = tag
                else:
                    payload["items"] = [item.model_dump(mode="json")]
                await conn.execute(
                    text(
                        "INSERT INTO events (id, shopping_list_id, user_id, type, source, payload) "
                        "VALUES (:id, :list, :user, :type, "
                        "CAST(:source AS jsonb), CAST(:payload AS jsonb))"
                    ),
                    {
                        "id": uuid7(),
                        "list": list_id,
                        "user": user_id,
                        "type": type.value,
                        "source": json.dumps({"kind": "app", "device_id": "phone"}),
                        "payload": json.dumps(payload),
                    },
                )
    finally:
        await engine.dispose()


async def _validate_migrated_events(url: str) -> list[dict[str, object]]:
    from sqlalchemy import select
    from sqlalchemy.ext.asyncio import async_sessionmaker

    from grocery.db.models import Event
    from grocery.schemas.events import EventRead, ShoppingListEventRead

    engine = create_async_engine(url)
    try:
        async with async_sessionmaker(engine)() as session:
            events = list(await session.scalars(select(Event).order_by(Event.type)))
            assert len(events) == 9
            return [
                ShoppingListEventRead.model_validate(
                    EventRead.model_validate(event).model_dump()
                ).model_dump(mode="json")
                for event in events
            ]
    finally:
        await engine.dispose()


def test_existing_event_payloads_survive_upgrade_and_downgrade(empty_database_url: str) -> None:
    config = alembic_config(empty_database_url)
    command.upgrade(config, "0004")
    asyncio.run(_seed_legacy_event_payloads(empty_database_url))
    command.upgrade(config, "head")
    first = asyncio.run(_validate_migrated_events(empty_database_url))
    command.downgrade(config, "0004")
    command.upgrade(config, "head")
    assert asyncio.run(_validate_migrated_events(empty_database_url)) == first
