"""Миграции: совпадение с моделями и stairway-тест (ADR-0011, ADR-0013).

Тесты синхронные: env.py Alembic сам запускает asyncio.run().
"""

import asyncio

import pytest
from alembic import command
from alembic.script import ScriptDirectory
from sqlalchemy import make_url, text
from sqlalchemy.ext.asyncio import create_async_engine
from testcontainers.community.postgres import PostgresContainer

from tests.support import alembic_config

DATABASE = "migrations_check"


async def _recreate_database(admin_url: str) -> None:
    engine = create_async_engine(admin_url, isolation_level="AUTOCOMMIT")
    async with engine.connect() as connection:
        await connection.execute(text('DROP DATABASE IF EXISTS "migrations_check"'))
        await connection.execute(text('CREATE DATABASE "migrations_check"'))
    await engine.dispose()


@pytest.fixture
def empty_database_url(postgres: PostgresContainer) -> str:
    """Отдельная пустая база в том же контейнере — не мешает основной тестовой."""
    admin_url = postgres.get_connection_url()
    asyncio.run(_recreate_database(admin_url))
    return make_url(admin_url).set(database=DATABASE).render_as_string(hide_password=False)


def test_upgrade_head_matches_models(empty_database_url: str) -> None:
    config = alembic_config(empty_database_url)

    command.upgrade(config, "head")

    # AutogenerateDiffsDetected, если модели и миграции разошлись.
    command.check(config)


def test_stairway(empty_database_url: str) -> None:
    config = alembic_config(empty_database_url)
    revisions = list(ScriptDirectory.from_config(config).walk_revisions("base", "heads"))

    assert revisions, "нет ни одной миграции"
    for revision in reversed(revisions):
        command.upgrade(config, revision.revision)
        command.downgrade(config, "-1")
        command.upgrade(config, revision.revision)
