/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get */
        get: operations["get_api_items_get"];
        put?: never;
        /** Add */
        post: operations["add_api_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/bought": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bought */
        post: operations["bought_api_items_bought_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/clear-bought": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear */
        post: operations["clear_api_items_clear_bought_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/quick-add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Quick Add */
        post: operations["quick_add_api_items_quick_add_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete */
        delete: operations["delete_api_items__id__delete"];
        options?: never;
        head?: never;
        /** Update */
        patch: operations["update_api_items__id__patch"];
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get */
        get: operations["get_api_tags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete */
        delete: operations["delete_api_tags__id__delete"];
        options?: never;
        head?: never;
        /** Rename */
        patch: operations["rename_api_tags__id__patch"];
        trace?: never;
    };
    "/api/tags/{id}/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk */
        post: operations["bulk_api_tags__id__bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddItemResult */
        AddItemResult: {
            item: components["schemas"]["ItemRead"];
            status: components["schemas"]["AddStatus"];
        };
        /** AddItems */
        AddItems: {
            /** Items */
            items: components["schemas"]["ItemCreate"][];
            /**
             * Shopping List Id
             * Format: uuid
             */
            shopping_list_id: string;
        };
        /**
         * AddStatus
         * @enum {string}
         */
        AddStatus: "created" | "merged";
        /** AppAttribution */
        AppAttribution: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "app";
        };
        /** AppSource */
        AppSource: {
            /** Device Id */
            device_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "app";
        };
        /** BoughtClearedEvent */
        BoughtClearedEvent: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            payload: components["schemas"]["EventPayload"];
            /**
             * Shopping List Id
             * Format: uuid
             */
            shopping_list_id: string;
            /** Source */
            source: components["schemas"]["AppSource"] | components["schemas"]["McpSource"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "bought_cleared";
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** ClearBought */
        ClearBought: {
            /**
             * Shopping List Id
             * Format: uuid
             */
            shopping_list_id: string;
        };
        /** CountRead */
        CountRead: {
            /** Count */
            count: number;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Loc */
            loc: (string | number)[];
            /** Message */
            message: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Code */
            code: string;
            /** Details */
            details?: components["schemas"]["ErrorDetail"][] | null;
            /** Message */
            message: string;
        };
        /** EventPayload */
        EventPayload: {
            /** Items */
            items?: components["schemas"]["ItemRead"][];
            previous_tag?: components["schemas"]["TagRead"] | null;
            /** Results */
            results?: components["schemas"]["AddItemResult"][];
            tag?: components["schemas"]["TagRead"] | null;
        };
        /** HealthRead */
        HealthRead: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "unavailable";
            /** Version */
            version: string;
        };
        /** ItemCreate */
        ItemCreate: {
            /** Name */
            name: string;
            /** Note */
            note?: string | null;
            /** Quantity */
            quantity?: number | string | null;
            /** Tags */
            tags?: string[];
            /** Unit */
            unit?: string | null;
        };
        /** ItemRead */
        ItemRead: {
            /** Bought At */
            bought_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Bought */
            is_bought: boolean;
            /** Name */
            name: string;
            /** Note */
            note: string | null;
            /** Quantity */
            quantity: number | null;
            /**
             * Shopping List Id
             * Format: uuid
             */
            shopping_list_id: string;
            /** Sources */
            sources: (components["schemas"]["AppAttribution"] | components["schemas"]["McpAttribution"])[];
            /** Tags */
            tags: components["schemas"]["TagRead"][];
            /** Unit */
            unit: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ItemUpdate */
        ItemUpdate: {
            /** Name */
            name?: string | null;
            /** Note */
            note?: string | null;
            /** Quantity */
            quantity?: number | string | null;
            /** Tags */
            tags?: string[] | null;
            /** Unit */
            unit?: string | null;
        };
        /** ItemUpdatedEvent */
        ItemUpdatedEvent: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            payload: components["schemas"]["EventPayload"];
            /**
             * Shopping List Id
             * Format: uuid
             */
            shopping_list_id: string;
            /** Source */
            source: components["schemas"]["AppSource"] | components["schemas"]["McpSource"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "item_updated";
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** ItemsAddedEvent */
        ItemsAddedEvent: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            payload: components["schemas"]["EventPayload"];
            /**
             * Shopping List Id
             * Format: uuid
             */
            shopping_list_id: string;
            /** Source */
            source: components["schemas"]["AppSource"] | components["schemas"]["McpSource"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "items_added";
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** ItemsBoughtEvent */
        ItemsBoughtEvent: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            payload: components["schemas"]["EventPayload"];
            /**
             * Shopping List Id
             * Format: uuid
             */
            shopping_list_id: string;
            /** Source */
            source: components["schemas"]["AppSource"] | components["schemas"]["McpSource"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "items_bought";
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** ItemsDeletedEvent */
        ItemsDeletedEvent: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            payload: components["schemas"]["EventPayload"];
            /**
             * Shopping List Id
             * Format: uuid
             */
            shopping_list_id: string;
            /** Source */
            source: components["schemas"]["AppSource"] | components["schemas"]["McpSource"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "items_deleted";
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** ItemsUnboughtEvent */
        ItemsUnboughtEvent: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            payload: components["schemas"]["EventPayload"];
            /**
             * Shopping List Id
             * Format: uuid
             */
            shopping_list_id: string;
            /** Source */
            source: components["schemas"]["AppSource"] | components["schemas"]["McpSource"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "items_unbought";
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** LoginCreate */
        LoginCreate: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** McpAttribution */
        McpAttribution: {
            /** Client Name */
            client_name: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "mcp";
        };
        /** McpSource */
        McpSource: {
            /** Client Id */
            client_id: string;
            /** Client Name */
            client_name: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "mcp";
        };
        /** MeRead */
        MeRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Shopping Lists */
            shopping_lists: components["schemas"]["ShoppingListRead"][];
            /** Username */
            username: string;
        };
        /** ParsedItem */
        ParsedItem: {
            /** Name */
            name: string;
            /** Quantity */
            quantity?: number | null;
            /** Unit */
            unit?: string | null;
        };
        /** QuickAdd */
        QuickAdd: {
            /**
             * Shopping List Id
             * Format: uuid
             */
            shopping_list_id: string;
            /** Tags */
            tags?: string[];
            /** Text */
            text: string;
        };
        /** QuickAddResult */
        QuickAddResult: {
            parsed: components["schemas"]["ParsedItem"];
            result: components["schemas"]["AddItemResult"];
        };
        /** SetBought */
        SetBought: {
            /** Bought */
            bought: boolean;
            /** Ids */
            ids: string[];
            /**
             * Shopping List Id
             * Format: uuid
             */
            shopping_list_id: string;
        };
        /**
         * ShoppingListEventRead
         * @description Named SSE contract; serialized as the original event object.
         */
        ShoppingListEventRead: components["schemas"]["ItemsAddedEvent"] | components["schemas"]["ItemUpdatedEvent"] | components["schemas"]["ItemsBoughtEvent"] | components["schemas"]["ItemsUnboughtEvent"] | components["schemas"]["ItemsDeletedEvent"] | components["schemas"]["BoughtClearedEvent"] | components["schemas"]["TagRenamedEvent"] | components["schemas"]["TagsMergedEvent"] | components["schemas"]["TagDeletedEvent"];
        /** ShoppingListRead */
        ShoppingListRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** TagBulk */
        TagBulk: {
            /**
             * Action
             * @enum {string}
             */
            action: "mark_bought" | "delete_items";
        };
        /** TagDeletedEvent */
        TagDeletedEvent: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            payload: components["schemas"]["EventPayload"];
            /**
             * Shopping List Id
             * Format: uuid
             */
            shopping_list_id: string;
            /** Source */
            source: components["schemas"]["AppSource"] | components["schemas"]["McpSource"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "tag_deleted";
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** TagRead */
        TagRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** TagRenamedEvent */
        TagRenamedEvent: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            payload: components["schemas"]["EventPayload"];
            /**
             * Shopping List Id
             * Format: uuid
             */
            shopping_list_id: string;
            /** Source */
            source: components["schemas"]["AppSource"] | components["schemas"]["McpSource"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "tag_renamed";
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** TagUpdate */
        TagUpdate: {
            /** Name */
            name: string;
        };
        /** TagUsageRead */
        TagUsageRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Open Count */
            open_count: number;
        };
        /** TagsMergedEvent */
        TagsMergedEvent: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            payload: components["schemas"]["EventPayload"];
            /**
             * Shopping List Id
             * Format: uuid
             */
            shopping_list_id: string;
            /** Source */
            source: components["schemas"]["AppSource"] | components["schemas"]["McpSource"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "tags_merged";
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header: {
                "X-Device-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeRead"];
                };
            };
            /** @description Требуется вход или неверные учётные данные */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Некорректный запрос */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Слишком много попыток входа */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Внутренняя ошибка */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header: {
                "X-Device-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Требуется вход или неверные учётные данные */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Объект не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Конфликт */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Некорректный запрос */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Внутренняя ошибка */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    events_api_events_get: {
        parameters: {
            query: {
                shopping_list_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Требуется вход или неверные учётные данные */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Объект не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Конфликт */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Некорректный запрос */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Внутренняя ошибка */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthRead"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthRead"];
                };
            };
        };
    };
    get_api_items_get: {
        parameters: {
            query: {
                shopping_list_id: string;
                include_bought?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemRead"][];
                };
            };
            /** @description Требуется вход или неверные учётные данные */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Объект не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Конфликт */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Некорректный запрос */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Внутренняя ошибка */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    add_api_items_post: {
        parameters: {
            query?: never;
            header: {
                "X-Device-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddItems"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddItemResult"][];
                };
            };
            /** @description Требуется вход или неверные учётные данные */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Объект не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Конфликт */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Некорректный запрос */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Внутренняя ошибка */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    bought_api_items_bought_post: {
        parameters: {
            query?: never;
            header: {
                "X-Device-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetBought"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemRead"][];
                };
            };
            /** @description Требуется вход или неверные учётные данные */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Объект не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Конфликт */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Некорректный запрос */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Внутренняя ошибка */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    clear_api_items_clear_bought_post: {
        parameters: {
            query?: never;
            header: {
                "X-Device-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClearBought"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountRead"];
                };
            };
            /** @description Требуется вход или неверные учётные данные */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Объект не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Конфликт */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Некорректный запрос */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Внутренняя ошибка */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    quick_add_api_items_quick_add_post: {
        parameters: {
            query?: never;
            header: {
                "X-Device-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuickAdd"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuickAddResult"];
                };
            };
            /** @description Требуется вход или неверные учётные данные */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Объект не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Конфликт */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Некорректный запрос */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Внутренняя ошибка */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_api_items__id__delete: {
        parameters: {
            query?: never;
            header: {
                "X-Device-Id": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Требуется вход или неверные учётные данные */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Объект не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Конфликт */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Некорректный запрос */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Внутренняя ошибка */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_api_items__id__patch: {
        parameters: {
            query?: never;
            header: {
                "X-Device-Id": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemRead"];
                };
            };
            /** @description Требуется вход или неверные учётные данные */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Объект не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Конфликт */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Некорректный запрос */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Внутренняя ошибка */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeRead"];
                };
            };
            /** @description Требуется вход или неверные учётные данные */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Объект не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Конфликт */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Некорректный запрос */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Внутренняя ошибка */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_api_tags_get: {
        parameters: {
            query: {
                shopping_list_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagUsageRead"][];
                };
            };
            /** @description Требуется вход или неверные учётные данные */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Объект не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Конфликт */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Некорректный запрос */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Внутренняя ошибка */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_api_tags__id__delete: {
        parameters: {
            query?: never;
            header: {
                "X-Device-Id": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Требуется вход или неверные учётные данные */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Объект не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Конфликт */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Некорректный запрос */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Внутренняя ошибка */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    rename_api_tags__id__patch: {
        parameters: {
            query?: never;
            header: {
                "X-Device-Id": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagRead"];
                };
            };
            /** @description Требуется вход или неверные учётные данные */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Объект не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Конфликт */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Некорректный запрос */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Внутренняя ошибка */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    bulk_api_tags__id__bulk_post: {
        parameters: {
            query?: never;
            header: {
                "X-Device-Id": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagBulk"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountRead"];
                };
            };
            /** @description Требуется вход или неверные учётные данные */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Объект не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Конфликт */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Некорректный запрос */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Внутренняя ошибка */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
